name: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - name: Enforce formatting
        run: cargo fmt --check

  # test:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout Repo 
  #     uses: actions/checkout@v3
  #   - name: Run tests
  #     run: cargo test --verbose